export const SOCKET_MESSAGE_EVENTS = {
	'group.leftConfirm': 'left',
	'group.left': 'user-left',
	'group.leave': 'leave-group',
	'group.joinConfirm': 'joined',
	'group.joined': 'user-joined',
	'group.join': 'join-group',
	'group.alreadyJoined': 'already-joined',
	'message.editConf': 'message-edited',
	'message.edit': 'edit-message',
	'message.deleteConf': 'message-deleted',
	'message.delete': 'delete-message',
	'message.recieve': 'recieve-message',
	'message.sendConf': 'message-sent',
	'message.send': 'send-message',
  'conversation.create': 'conversation-created',
	'user.status': 'user-status',
	'user.updateStatus': 'update-status',
	error: 'error',
	disconnect: 'disconnect',
};